# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptannaReact' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  platform :ios, '9.0'

  # Pods for CryptannaReact
  # Required by RNFirebase
pod 'Firebase/Core', '~> 6.3.0'
pod 'Firebase/Auth', '~> 6.3.0'
pod 'Firebase/Firestore', '~> 6.3.0'

  target 'CryptannaReact-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'CryptannaReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CryptannaReact-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CryptannaReact-tvOS
end
